"""Generate browser demo candidate costs from the Python planner, not a second rate engine."""
import json
from pathlib import Path
from premium_model_budget_governor.workflow import plan_workflow

ROOT = Path(__file__).resolve().parents[1]


def main():
    packet = json.loads((ROOT / "examples/astra_preferred.json").read_text())
    packet.update(budget_credits=100, remaining_limit_percent=50)
    data = {}
    for floor in [0, 24000, 38000]:
        packet["minimum_input_tokens_per_call"] = floor
        data[str(floor)] = plan_workflow(packet)["candidates"]
    output = "// Generated by scripts/build_demo_data.py; illustrative estimates, not live billing.\nwindow.DEMO_WORKFLOWS = " + json.dumps(data, indent=2) + ";\n"
    (ROOT / "site/workflows.js").write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
