const { chromium } = require("playwright");
const fs = require("fs");
const path = require("path");
const assert = require("assert/strict");
(async () => {
  const root = path.resolve(__dirname, "..");
  const url = JSON.parse(fs.readFileSync(path.join(root,"build/local-ui-session.json"),"utf8")).url;
  const output = path.join(root,"artifacts/workbench-qa");
  fs.mkdirSync(output,{recursive:true});
  const browser=await chromium.launch({headless:true});
  const records=[];
  try {
    for(const width of [1440,390,320]) {
      const page=await browser.newPage({viewport:{width,height:1000}});
      const errors=[];
      page.on("pageerror",e=>errors.push(e.message));
      page.on("console",m=>{if(m.type()==="error") errors.push(m.text());});
      await page.goto(url,{waitUntil:"load"});
      await page.getByText("Local session connected. No run started.",{exact:true}).waitFor();
      // Redact in the QA DOM before any capture; focus scrolling can offset screenshot masks.
      await page.locator("#project-path").evaluate(el=>{el.textContent="Local QA project (path omitted)";});
      assert(!page.url().includes("session="));
      let pickerResult={status:"selected",path:"C:/Public QA/project"};
      await page.route("**/api/projects/choose",route=>{
        assert.deepEqual(route.request().postDataJSON(),{open:true});
        return route.fulfill({json:{ok:true,result:pickerResult}});
      });
      await page.getByRole("button",{name:"Manage projects",exact:true}).click();
      await page.locator("#new-project-path").fill("C:/Previous folder");
      await page.locator("#project-consent").check();
      await page.locator("#choose-project").click();
      await page.getByText("Folder selected. Review and approve access before adding it.",{exact:true}).waitFor();
      assert.equal(await page.locator("#new-project-path").inputValue(),"C:/Public QA/project");
      assert(!(await page.locator("#project-consent").isChecked()));
      pickerResult={status:"canceled"};
      await page.locator("#choose-project").click();
      await page.getByText("Selection canceled. Nothing added.",{exact:true}).waitFor();
      assert.equal(await page.locator("#new-project-path").inputValue(),"C:/Public QA/project");
      pickerResult={status:"unavailable"};
      await page.locator("#choose-project").click();
      await page.getByText("Folder chooser unavailable. Enter the absolute folder path instead.",{exact:true}).waitFor();
      await page.locator("#saved-projects .path").evaluateAll(elements=>elements.forEach(el=>{el.textContent="Local QA project (path omitted)";}));
      await page.locator("#projects-dialog").screenshot({path:path.join(output,`folder-chooser-${width}.png`)});
      await page.locator("#close-projects").click();
      await page.unroute("**/api/projects/choose");
      await page.locator("#project-path").evaluate(el=>{el.textContent="Local QA project (path omitted)";});
      await page.locator("#task").fill("Review the supplied planning example for budget accounting risks.");
      await page.locator("#family").selectOption("review");
      await page.getByRole("button",{name:"Browse files",exact:true}).click();
      await page.getByRole("button",{name:"Add astra_preferred.json",exact:true}).click();
      assert.equal(await page.locator("#evidence").inputValue(),"astra_preferred.json");
      await page.getByRole("button",{name:"Browse images",exact:true}).click();
      await page.getByRole("button",{name:"Add benchmark_v3.png",exact:true}).click();
      assert.equal(await page.locator("#images").inputValue(),"benchmark_v3.png");
      const responsePromise=page.waitForResponse(r=>r.url().endsWith("/api/preview")&&r.request().method()==="POST");
      await page.getByRole("button",{name:"Preview workflow",exact:true}).click();
      const savedResponse=await (await responsePromise).json();
      assert(savedResponse.ok,"Live preview rejected; no execution requested");
      await page.getByText("Ready for your approval",{exact:true}).waitFor({timeout:90000});
      assert.equal(savedResponse.result.policy_scope.family,"review");
      assert.equal(await page.locator("#model").textContent(),"gpt-6-astra");
      assert(await page.locator("#run").isDisabled());
      const pixels=await page.locator("canvas").evaluate(c=>Array.from(c.getContext("2d").getImageData(0,0,800,40).data).some((v,i)=>i%4===3&&v>0));
      assert(pixels);
      await page.screenshot({path:path.join(output,`${width}.png`),fullPage:true,mask:[page.locator("#project-path")],maskColor:"#e2e5e7"});
      await page.locator("#strategy").selectOption("prepared");
      await page.locator("#budget").fill("40");
      const multiResponse=page.waitForResponse(r=>r.url().endsWith("/api/preview")&&r.request().method()==="POST");
      await page.locator("#preview-button").click();
      const multi=(await (await multiResponse).json()).result;
      assert.equal(multi.strategy,"prepared");
      assert.equal(multi.plan.selected.stages.length,2);
      await page.getByText("Ready for your approval",{exact:true}).waitFor();
      assert.equal(await page.locator("#stage-breakdown li").count(),2);
      await page.screenshot({path:path.join(output,`prepared-${width}.png`),fullPage:true});
      // Receipt rendering only: intercept execution before any real dispatch.
      await page.route("**/api/execute",route=>route.fulfill({status:202,json:{ok:true,result:{status:"queued"}}}));
      await page.route("**/api/jobs/*",route=>route.fulfill({json:{ok:true,result:{status:"completed",result:{status:"completed",answer:"Simulated two-stage receipt; no model calls.",estimated_credits:.35,stages:[{actual_model:"gpt-5.6-sol",credits:.1,usage:{input_tokens:1000,cached_tokens:0,output_tokens:0}},{actual_model:"gpt-6-astra",credits:.25,usage:{input_tokens:1000,cached_tokens:0,output_tokens:0}}]}}}}));
      await page.locator("#approval").check(); await page.locator("#run").click();
      await page.getByText("Simulated two-stage receipt; no model calls.",{exact:true}).waitFor();
      assert.equal(await page.locator(".stage-receipt").count(),2);
      assert(await page.locator("#run-status").evaluate(el=>el.getBoundingClientRect().height<30),"short status should not split across lines");
      assert.equal(await page.locator("#receipt > div").filter({has:page.getByText("Input tokens",{exact:true})}).locator("dd").textContent(),"2000");
      await page.screenshot({path:path.join(output,`stage-receipt-${width}.png`),fullPage:true});
      // Renderer fixtures only: never submit another execution for accounting variants.
      await page.evaluate(()=>showReceipt({status:"unknown_usage",cost_complete:false,estimated_credits:null,known_estimated_credits:.1,budget:{reserved_credits:4},stages:[{actual_model:"gpt-5.6-sol",credits:.1,usage:{input_tokens:1000,cached_tokens:0,output_tokens:0}}]}));
      await page.locator("#run-status").evaluate(el=>{el.textContent="unknown usage";});
      await page.locator("#answer").evaluate(el=>{el.textContent="Simulated partial receipt; no model calls.";});
      const receiptValue = name => page.locator("#receipt > div").filter({has:page.getByText(name,{exact:true})}).locator("dd").textContent();
      assert.equal(await receiptValue("Known input tokens"),"1000");
      assert.equal(await receiptValue("Projected credits"),"Unknown");
      assert.equal(await receiptValue("Known projected credits"),"0.100");
      assert.equal(await receiptValue("Still reserved"),"4.000");
      await page.screenshot({path:path.join(output,`partial-receipt-${width}.png`),fullPage:true});
      assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"partial receipt overflow");
      await page.evaluate(()=>showReceipt({status:"completed",estimated_credits:.35,stages:[{usage:{input_tokens:1000,output_tokens:0}},{usage:{input_tokens:1000,cached_tokens:0,output_tokens:0}}]}));
      assert.equal(await receiptValue("Input tokens"),"2000");
      assert.equal(await receiptValue("Cached tokens"),"Unknown");
      assert.equal(await receiptValue("Output tokens"),"0");
      await page.evaluate(()=>showReceipt({status:"unknown_usage",estimated_credits:0,stages:[]}));
      assert.equal(await receiptValue("Known input tokens"),"Unknown");
      assert.equal(await receiptValue("Known projected credits"),"Unknown");
      assert.equal(await receiptValue("Projected credits"),"Unknown");
      await page.unroute("**/api/execute"); await page.unroute("**/api/jobs/*");
      await page.locator("#strategy").selectOption("direct"); await page.locator("#budget").fill("20");
      await page.locator("#preview-button").click(); await page.getByText("Ready for your approval",{exact:true}).waitFor();
      await page.locator("#approval").check();
      assert(!(await page.locator("#run").isDisabled()));
      await page.locator("#task").fill("Changed task requires a new preview.");
      assert(await page.locator("#preview").isHidden());
      assert(await page.locator("#run").isDisabled());
      await page.getByRole("button",{name:"Usage",exact:true}).click();
      assert(await page.locator("#usage-view").isVisible());
      await page.getByRole("button",{name:"Task",exact:true}).click();
      if(width===1440){
        await page.route("**/api/preview",async route=>{await new Promise(resolve=>setTimeout(resolve,150));await route.fulfill({json:savedResponse});});
        await page.getByRole("button",{name:"Preview workflow",exact:true}).click();
        await page.locator("#task").fill("Changed while the preview response was pending.");
        await page.getByText("Task changed while previewing. Review the updated task again.",{exact:true}).waitFor();
        assert(await page.locator("#preview").isHidden());
        await page.getByRole("button",{name:"Preview workflow",exact:true}).click();
        await page.getByText("Ready for your approval",{exact:true}).waitFor();
        // Browser rendering fixture only: intercept execution, never send a paid call.
        await page.route("**/api/execute",route=>route.fulfill({status:202,json:{ok:true,result:{status:"queued"}}}));
        await page.route("**/api/jobs/*",route=>route.fulfill({json:{ok:true,result:{status:"completed",result:{status:"completed",answer:"Simulated UI receipt (no model call).",usage:{input_tokens:5000,cached_tokens:0,output_tokens:0},estimated_credits:1.25}}}}));
        await page.locator("#approval").check();await page.locator("#run").click();
        await page.getByText("Simulated UI receipt (no model call).",{exact:true}).waitFor();
        assert(await page.locator("#receipt").isVisible());
        assert((await page.locator("#receipt").textContent()).includes("1.250"));
        await page.getByRole("button",{name:"Preview workflow",exact:true}).click();
        await page.getByText("Ready for your approval",{exact:true}).waitFor();
        let broken=true, stopped=false;
        await page.unroute("**/api/jobs/*");
        await page.route("**/api/jobs/*",route=>{
          if(broken){broken=false;return route.fulfill({contentType:"application/json",body:"{"});}
          return route.fulfill({json:{ok:true,result:stopped ? {status:"unknown_usage",result:{status:"unknown_usage",stop_requested:true,answer:"Simulated stop receipt (no model call).",budget:{reserved_credits:10}}} : {status:"running"}}});
        });
        await page.route("**/api/cancel",route=>{stopped=true;return route.fulfill({status:202,json:{ok:true,result:{status:"stop_requested"}}});});
        await page.locator("#approval").check();await page.locator("#run").click();
        await page.locator("#reconnect").waitFor({state:"visible"});
        assert(await page.locator("#preview-button").isDisabled());
        await page.locator("#reconnect").click();
        await page.locator("#stop").click();
        await page.getByText("Simulated stop receipt (no model call).",{exact:true}).waitFor();
        assert((await page.locator("#receipt").textContent()).includes("10.000"));
      }
      // Explicit fixture: recovery must not submit a task or accept browser token counters.
      let recovered=false;
      await page.route("**/api/history", route=>route.fulfill({json:{ok:true,result:[{id:"f".repeat(32),status:recovered ? "usage_recovered" : "unknown_usage",estimated_credits:recovered ? 1.25 : null}]}}));
      await page.route("**/api/reconcile", route=>{
        assert.deepEqual(route.request().postDataJSON(),{id:"f".repeat(32),approved:true});
        recovered=true;
        return route.fulfill({json:{ok:true,result:{status:"usage_recovered",message:"Simulated receipt recovered. No run started."}}});
      });
      await page.getByRole("button",{name:"Usage",exact:true}).click();
      await page.getByRole("button",{name:"Recover recorded usage",exact:true}).click();
      await page.getByText("usage_recovered",{exact:true}).waitFor();
      assert((await page.locator("#history").textContent()).includes("1.250"));
      await page.screenshot({path:path.join(output,`recovery-${width}.png`),fullPage:true});
      await page.getByRole("button",{name:"Task",exact:true}).click();
      await page.locator("#images").fill("");
      await page.route("**/api/doctor", route=>route.fulfill({json:{ok:true,result:{governor_version:"0.4.0rc2",python:{version:"3.13.7"},codex:{found:true,version:"0.153.4"},mcp:{installed:false,version:"PRIVATE_SENTINEL"},model_execution:"needs_attention",authentication:{status:"unavailable",account:"PRIVATE_SENTINEL"},raw_log:"PRIVATE_SENTINEL",next_steps:["PRIVATE_SENTINEL"]}}}));
      await page.route("**/api/host-options", route=>route.fulfill({json:{ok:true,result:{models:[{model:"gpt-6-astra",reasoning_efforts:["max"],input_modalities:["text"]}]}}}));
      await page.getByRole("button",{name:"Check setup",exact:true}).click();
      await page.getByText("Previous choice unavailable. Select a supported level.",{exact:true}).waitFor();
      await page.getByText("Run codex login in your own terminal, then check setup again.",{exact:true}).waitFor();
      const downloadEvent = page.waitForEvent("download");
      await page.getByRole("button",{name:"Download setup report",exact:true}).click();
      const download = await downloadEvent;
      assert.equal(download.suggestedFilename(),"governor-setup-report.json");
      const exported = fs.readFileSync(await download.path(),"utf8");
      assert(!exported.includes("PRIVATE_SENTINEL"));
      assert(!exported.includes("session="));
      assert.deepEqual(JSON.parse(exported),{schema_version:1,governor_version:"0.4.0rc2",python_version:"3.13.7",codex_version:"0.153.4",mcp_version:null,codex_found:true,mcp_installed:false,authentication:"unavailable",model_execution:"needs_attention",model_access_verified:false,model_calls_started:0});
      await page.screenshot({path:path.join(output,`setup-${width}.png`),fullPage:true});
      await page.locator("#close-setup").click();
      await page.unroute("**/api/doctor");
      await page.route("**/api/doctor", route=>route.fulfill({json:{ok:false,error:"Setup check unavailable. Try again."}}));
      await page.getByRole("button",{name:"Check setup",exact:true}).click();
      await page.getByText("Setup check unavailable. Try again.",{exact:true}).waitFor();
      assert(await page.locator("#download-diagnostics").isDisabled());
      assert.equal(await page.locator("#setup-next").textContent(),"");
      await page.locator("#close-setup").click();
      assert.equal(await page.locator("#effort").inputValue(),"low");
      assert.equal(await page.locator("#effort").evaluate(el=>el.checkValidity()),false);
      await page.locator("#effort").selectOption("max");
      assert.equal(await page.locator("#effort").evaluate(el=>el.checkValidity()),true);
      await page.locator("#images").fill("benchmark_v3.png");
      assert.equal(await page.locator("#effort").inputValue(),"max");
      assert.equal(await page.locator("#effort").evaluate(el=>el.checkValidity()),false);
      await page.getByText("No compatible host options. Check setup.",{exact:true}).waitFor();
      await page.locator("#images").fill("");
      await page.unroute("**/api/preview");
      await page.route("**/api/preview", route=>route.fulfill({json:{ok:false,code:"evidence_invalid",field:"evidence",error:"Choose readable project evidence."}}));
      await page.getByRole("button",{name:"Preview workflow",exact:true}).click();
      await page.locator("#evidence-error").waitFor({state:"visible"});
      assert.equal(await page.locator("#evidence").getAttribute("aria-invalid"),"true");
      assert.equal(await page.evaluate(()=>document.activeElement.id),"evidence");
      await page.screenshot({path:path.join(output,`field-error-${width}.png`),fullPage:true,mask:[page.locator("#project-path")],maskColor:"#e2e5e7"});
      await page.locator("#evidence").fill("");
      assert(await page.locator("#evidence-error").isHidden());
      const projectFolder=path.join(root,"build","qa-registered-project");
      fs.mkdirSync(projectFolder,{recursive:true});
      await page.getByRole("button",{name:"Manage projects",exact:true}).click();
      await page.locator("#new-project-path").fill(projectFolder);
      assert(!(await page.locator("#project-consent").isChecked()));
      await page.locator("#project-consent").check();
      await page.getByRole("button",{name:"Add project",exact:true}).click();
      await page.getByText("Project saved and selected. No model run started.",{exact:true}).waitFor();
      assert((await page.locator("#project").inputValue()).startsWith("saved-"));
      await page.getByRole("button",{name:"Remove qa-registered-project",exact:true}).click();
      await page.getByText("Project removed from the list. Files and usage history were not deleted.",{exact:true}).waitFor();
      assert.equal(await page.getByRole("button",{name:"Remove qa-registered-project",exact:true}).count(),0);
      assert(fs.existsSync(projectFolder));
      await page.getByRole("button",{name:"Close",exact:true}).filter({visible:true}).click();
      const actualProjects=await page.evaluate(async()=>{
        const select=document.getElementById("project");
        return Array.from(select.options).map(option=>({id:option.value,name:option.textContent,path:"Local QA project",available:true,removable:false}));
      });
      await page.route("**/api/projects", route=>route.fulfill({json:{ok:true,result:[...actualProjects,{id:"saved-missing",name:"Missing QA folder",path:"Local QA missing folder",available:false,removable:true}]}}));
      await page.getByRole("button",{name:"Manage projects",exact:true}).click();
      await page.locator("#new-project-path").fill("Local QA path omitted");
      await page.getByText("Unavailable folder. Remove this registration or restore the folder and restart.",{exact:true}).waitFor();
      assert.equal(await page.locator('#project option[value="saved-missing"]').count(),0);
      assert(await page.getByRole("button",{name:"Remove Missing QA folder",exact:true}).isVisible());
      await page.locator("#projects-dialog").screenshot({path:path.join(output,`missing-project-${width}.png`)});
      await page.locator("#close-projects").click();
      await page.unroute("**/api/projects");
      let aliasRemoved = false;
      await page.route("**/api/projects", route=>route.fulfill({json:{ok:true,result:[...actualProjects,...(aliasRemoved ? [] : [{id:"saved-alias",name:"Launch alias",path:"Local QA project",available:true,selectable:false,removable:true,configured_at_launch:true}])]}}));
      await page.route("**/api/projects/remove", route=>{
        assert.deepEqual(route.request().postDataJSON(),{id:"saved-alias",approved:true});
        aliasRemoved = true;
        return route.fulfill({json:{ok:true,result:{removed:true,files_deleted:false,launch_access_remains:true}}});
      });
      await page.getByRole("button",{name:"Manage projects",exact:true}).click();
      await page.getByText("Also configured at launch. Removing this saved registration does not remove launch access.",{exact:true}).waitFor();
      assert.equal(await page.locator('#project option[value="saved-alias"]').count(),0);
      await page.locator("#projects-dialog").screenshot({path:path.join(output,`launch-alias-${width}.png`)});
      await page.getByRole("button",{name:"Remove Launch alias",exact:true}).click();
      await page.getByText("Saved registration removed. Launch access remains until you change the launch command. Files and history were not deleted.",{exact:true}).waitFor();
      assert.equal(await page.locator("#project option").count(),actualProjects.length);
      await page.locator("#close-projects").click();
      const dimensions=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));
      assert(dimensions.scroll<=dimensions.width,"horizontal overflow");
      assert.deepEqual(errors,[]);
      records.push({width,dimensions,errors,live_host_preview:true,canvas_nonblank:pixels,file_picker:true,approval_invalidation:true,live_project_registration_removal:true,simulated_launch_alias_removal:true,simulated_field_errors:true,simulated_dynamic_efforts:true,simulated_receipt_recovery:true,diagnostic_download_allowlist_and_failure_reset:true,simulated_receipt_stop_reconnect_and_stale_preview_tested:width===1440,model_turns_started:0});
      await page.close();
      Object.assign(records.at(-1), {simulated_multistage_complete_partial_and_missing_counters:true,mobile_short_status_wrap_checked:true});
      records.at(-1).simulated_folder_choice_consent_cancel_and_fallback=true;
    }
  }finally{await browser.close();}
  fs.writeFileSync(path.join(output,"results.json"),JSON.stringify(records,null,2));
  console.log(JSON.stringify(records,null,2));
})().catch(error=>{console.error(error.message);process.exit(1);});
